### ISSUE TITLE
tars2case在使用时出core

### ISSUE THREAD

**Issue by R1cardoX** [TarsCloud/TarsCpp#207]
不清楚到底是什么问题 tars2cpp就可以完美运行,为什么tars2case运行成功率低? 每次接口调试时,上传协议解析必失败
`#0  0x00007f4c9d13bad2 in __cxxabiv1::__vmi_class_type_info::__do_dyncast(long, __cxxabiv1::__class_type_info::__sub_kind, __cxxabiv1::__class_type_info const*, void const*, __cxxabiv1::__class_type_info const*, void const*, __cxxabiv1::__class_type_info::__dyncast_result&) const () from /lib64/libstdc++.so.6
#1  0x00007f4c9d13bd1e in __cxxabiv1::__vmi_class_type_info::__do_dyncast(long, __cxxabiv1::__class_type_info::__sub_kind, __cxxabiv1::__class_type_info const*, void const*, __cxxabiv1::__class_type_info const*, void const*, __cxxabiv1::__class_type_info::__dyncast_result&) const () from /lib64/libstdc++.so.6
#2  0x00007f4c9d13bd1e in __cxxabiv1::__vmi_class_type_info::__do_dyncast(long, __cxxabiv1::__class_type_info::__sub_kind, __cxxabiv1::__class_type_info const*, void const*, __cxxabiv1::__class_type_info const*, void const*, __cxxabiv1::__class_type_info::__dyncast_result&) const () from /lib64/libstdc++.so.6
#3  0x00007f4c9d138941 in __dynamic_cast () from /lib64/libstdc++.so.6
#4  0x000000000041ce91 in tars::TC_AutoPtr<Builtin> tars::TC_AutoPtr<Builtin>::dynamicCast<Type>(tars::TC_AutoPtr<Type> const&)
    ()
#5  0x00000000004177f8 in Tars2Case::tocaseVector(tars::TC_AutoPtr<Vector> const&, std::string const&) const ()
#6  0x0000000000417359 in Tars2Case::toCase(tars::TC_AutoPtr<Type> const&, std::string const&) const ()
#7  0x00000000004171e3 in Tars2Case::tocaseStruct(tars::TC_AutoPtr<Struct> const&, std::string const&) const ()
#8  0x00000000004173e9 in Tars2Case::toCase(tars::TC_AutoPtr<Type> const&, std::string const&) const ()
#9  0x0000000000417848 in Tars2Case::tocaseVector(tars::TC_AutoPtr<Vector> const&, std::string const&) const ()
#10 0x0000000000417359 in Tars2Case::toCase(tars::TC_AutoPtr<Type> const&, std::string const&) const ()
#11 0x00000000004171e3 in Tars2Case::tocaseStruct(tars::TC_AutoPtr<Struct> const&, std::string const&) const ()
#12 0x00000000004173e9 in Tars2Case::toCase(tars::TC_AutoPtr<Type> const&, std::string const&) const ()
#13 0x0000000000417848 in Tars2Case::tocaseVector(tars::TC_AutoPtr<Vector> const&, std::string const&) const ()
#14 0x0000000000417359 in Tars2Case::toCase(tars::TC_AutoPtr<Type> const&, std::string const&) const ()
#15 0x00000000004171e3 in Tars2Case::tocaseStruct(tars::TC_AutoPtr<Struct> const&, std::string const&) const ()
#16 0x00000000004173e9 in Tars2Case::toCase(tars::TC_AutoPtr<Type> const&, std::string const&) const ()
#17 0x0000000000417848 in Tars2Case::tocaseVector(tars::TC_AutoPtr<Vector> const&, std::string const&) const ()
#18 0x0000000000417359 in Tars2Case::toCase(tars::TC_AutoPtr<Type> const&, std::string const&) const ()
#19 0x00000000004171e3 in Tars2Case::tocaseStruct(tars::TC_AutoPtr<Struct> const&, std::string const&) const ()
#20 0x00000000004173e9 in Tars2Case::toCase(tars::TC_AutoPtr<Type> const&, std::string const&) const ()
#21 0x0000000000417848 in Tars2Case::tocaseVector(tars::TC_AutoPtr<Vector> const&, std::string const&) const ()
#22 0x0000000000417359 in Tars2Case::toCase(tars::TC_AutoPtr<Type> const&, std::string const&) const ()
#23 0x00000000004171e3 in Tars2Case::tocaseStruct(tars::TC_AutoPtr<Struct> const&, std::string const&) const ()
#24 0x00000000004173e9 in Tars2Case::toCase(tars::TC_AutoPtr<Type> const&, std::string const&) const ()
#25 0x0000000000417848 in Tars2Case::tocaseVector(tars::TC_AutoPtr<Vector> const&, std::string const&) const ()
#26 0x0000000000417359 in Tars2Case::toCase(tars::TC_AutoPtr<Type> const&, std::string const&) const ()
#27 0x00000000004171e3 in Tars2Case::tocaseStruct(tars::TC_AutoPtr<Struct> const&, std::string const&) const ()
#28 0x00000000004173e9 in Tars2Case::toCase(tars::TC_AutoPtr<Type> const&, std::string const&) const ()`

**Comment by ruanshudong** [comment]
有协议文件么? 贴出来看看?
